### PR TITLE
connected to both API's and updated readme with github pages link

### PR DESCRIPTION
**Pull request by DavidTunnell**

### CODE REVIEW

**Comment by chrisclary20** [comment]
LGTM

**Review by chrisclary20 — APPROVED** [review]
Nice.

**Review by chrisclary20 — APPROVED** [review]
Approved

**Comment by Elrob92** [comment]
Looks good!

**Comment by DavidTunnell** [comment]
Test.

**Comment by DavidTunnell** [comment]
review

**Review by Elrob92 — APPROVED** [review]

**Review by DavidTunnell — COMMENTED** [review]
test

**Pull request merged**
